"""initial schema

Baseline migration. Creates the full V1 schema from the SQLAlchemy models so a
fresh database can be provisioned with `alembic upgrade head`. Subsequent schema
changes get their own autogenerated revisions (compare_type is on in env.py).

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-05
"""
from typing import Sequence, Union

from alembic import op

from app.db.models import Base

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
